import { useState, useEffect } from "react"
import PersonDetail from "./config/SessionStore"
import Head from "next/head"
import CheckEligible from "./checkeligible"
import Welcome from "./welcome"
import NavMenu from "./navmenu"

export default function Home() {
	const [personDetail] = useState(PersonDetail)
	const [mounted, setMounted] = useState(false);
	useEffect(() => {
		setMounted(true)
	}, [personDetail])

	return (
		mounted &&
		<>
			<Head>
				<title>ระบบจองเตียงผู้ป่วยโควิด</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/img/logo.png' />
			</Head>
			{personDetail ? (
        <>
					<NavMenu />
					<Welcome />
				</>
			) : (
        <CheckEligible />
			)}
		</>
	)
}
