import Head from 'next/head'
import CheckEligible from './component/CheckEligible'
import Navbar from './component/Navbar'
import Welcome from './component/Welcome'

export default function Home() {
  return (
    <div className='p-5'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Welcome/>
      <CheckEligible/>
    </div>
  )
}
