import { useState, useEffect } from "react"
import PersonDetail from "./config/SessionStore"
import Head from "next/head"
import CheckEligible from "./component/CheckEligible"
import Welcome from "./component/Welcome"
import Navbar from "./component/Navbar"

export default function Home() {
	const [personDetail] = useState(PersonDetail)
	useEffect(() => {}, [personDetail])

	return (
		<div className='p-1'>
			<Head>
				<title>ระบบจองเตียงผู้ป่วยโควิด</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/img/logo.png' />
			</Head>
			{personDetail ? (
        <>
					<Navbar />
					<Welcome />
				</>
			) : (
        <CheckEligible />
			)}
		</div>
	)
}
